# Generated by Django 3.2.9 on 2021-12-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('Hiring_date', models.DateField()),
            ],
        ),
    ]
